travis:
  secure:
    BINSTAR_TOKEN: YynCtFmJx8ws2rm0RBFN5Fgo0db6uOhEtl7U3jpqkaiIpA7Pc/d0El9ub2y9/fRR8xPYEyoNys+zCoKJ6NwAwdVX9UD1MEccd2Y1ZDKuT4w0xMBlap+c8pzmvzOO+EPzwgeTWSsNTt4HHuhV7y0h1OmP6WMrvzW42b6X20S3jRyvz6pBSb244oDRKOXS+VZLDfLbcHeYpGAPk0V4o2WaTkx5ZOXKwTx4ksJfnJp2r3IhM2r6aFpAYMD+xFGhV3QSx1rAQdVccXLeQlUNXf4bWfuhPLZT1I24vadcvxEikMbLR/Lx+dNKbdq2lr/a49rg9ABvGp1qVuh+bagW8kaHKh5VaNESqAdczC2xPnJF8UNGuTrqAI9qHZULvXDVUe3G1qDFrt7+u/jv9UiVzhs5zmcKP2kb0fI6MuUkK1m/Le9CbrXF27oWn6pim8MKhNbG8VwtuaJEI9KsZRlWFeyFEXgDX3V0yR01iXuga1BTt0cJk+4/vtpeEa5/PgmyxlSWr175HJFZ9Fn3G9RbtfkQ7DKchHTKbdCBdJlu68UGWghdf+I/+9KQRfqOmoxJi+IXAlR7A1hIhay0vDEQ9nsJJzawHWHFz3Mhsf4cTnfrHze2pX2Cq8wRtDGBRPkevilplCHvAEoQtbhIo5111StUuWZjEdMa6qMnwpk3In+i1t8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
